/*
	Location.h
	The implementation of properties and methods for the Location object.
	Generated by RRInnovation LLC
 */
#import "Location.h"
//#import "ArrayOfLocation.h"
#import "Foursquare2.h"
#import "UIImage+Base64Image.h"

@implementation Location
	@synthesize AutoStrikeAlarmDate = _AutoStrikeAlarmDate;
    @synthesize LargestStrikeCreatedDate = _LargestStrikeCreatedDate;
	@synthesize Category = _Category;
	@synthesize EmailId = _EmailId;
	@synthesize IsAutoStrikeOn = _IsAutoStrikeOn;
	@synthesize IsFavorite = _IsFavorite;
	@synthesize Latitude = _Latitude;
	@synthesize LocationAddress = _LocationAddress;
	@synthesize LocationId = _LocationId;
	@synthesize LocationList = _LocationList;
	@synthesize LocationName = _LocationName;
	@synthesize Message = _Message;
	@synthesize PhoneNo = _PhoneNo;
	@synthesize Photo = _Photo;
	@synthesize Status = _Status;
	@synthesize TotalStrike = _TotalStrike;
	@synthesize TotalStrom = _TotalStrom;
	@synthesize UserId = _UserId;
    @synthesize TotalFemale = _TotalFemale;
    @synthesize TotalMale = _TotalMale;
	@synthesize longitude = _longitude;
    @synthesize AverageAge = _AverageAge;
    @synthesize AverageFemale = _AverageFemale;
    @synthesize AverageMale = _AverageMale;
    @synthesize LargestStrikeCount =  _LargestStrikeCount;
    @synthesize FoursquareID = _FoursquareID;
    @synthesize TotalStromCount = _TotalStromCount;

	- (id) init
	{
		if(self = [super init])
		{
			self.AutoStrikeAlarmDate = nil;
			self.Category = nil;
			self.EmailId = nil;
			self.Latitude = nil;
			self.LocationAddress = nil;
			self.LocationList = [[[NSMutableArray alloc] init] autorelease];
			self.LocationName = nil;
			self.Message = nil;
			self.PhoneNo = nil;
			self.Photo = nil;
			self.Status = nil;
			self.longitude = nil;
            self.FoursquareID = nil;

		}
		return self;
	}

	

	- (id) initWithNode: (NSDictionary*) node
    {
            self.Category = [node valueForKey: @"Category"];
			self.EmailId = [node valueForKey: @"EmailId"];
			self.IsAutoStrikeOn = [[node valueForKey: @"IsAutoStrikeOn"] boolValue];
			self.IsFavorite = [[node valueForKey: @"IsFavorite"] boolValue];
			self.Latitude = [node valueForKey: @"Latitude"];
			self.LocationAddress = [node valueForKey: @"LocationAddress"];
			self.LocationId = [[node valueForKey: @"LocationId"] intValue];
			self.LocationName = [node valueForKey: @"LocationName"];
			self.Message = [node valueForKey: @"Message"];
			self.PhoneNo = [node valueForKey: @"PhoneNo"];
			self.Photo = [node valueForKey: @"Photo"];
			self.Status = [node valueForKey: @"Status"];
			self.TotalStrike = [[node valueForKey: @"TotalStrike"] intValue];
			self.TotalStrom = [[node valueForKey: @"TotalStrom"] intValue];
			self.UserId = [[node valueForKey: @"UserId"] intValue];
            
        
            self.AverageAge = [[node valueForKey: @"AverageAge"] intValue];
            self.AverageFemale = [[node valueForKey: @"AverageFemale"] intValue];
            self.AverageMale = [[node valueForKey: @"AverageMale"] intValue];
            self.LargestStrikeCount = [[node valueForKey: @"LargestStrikeCount"] intValue];
        
            if (![[node valueForKey: @"TotalFemale"] isKindOfClass:[NSNull class]])
            {
                self.TotalFemale = [[node valueForKey: @"TotalFemale"] intValue];
                
            }
            if (![[node valueForKey: @"TotalMale"] isKindOfClass:[NSNull class]])
            {
                 self.TotalMale = [[node valueForKey: @"TotalMale"] intValue];
                
            }
        
            if (![[node valueForKey: @"LargestStrikeCreatedDate"] isKindOfClass:[NSNull class]])
            {
                self.LargestStrikeCreatedDate = [node valueForKey: @"LargestStrikeCreatedDate"] ;
            }

        
        
			self.longitude = [node valueForKey: @"longitude"];
            self.FoursquareID = [node objectForKey:@"FSLocationId"];
            self.TotalStromCount = [[node valueForKey: @"TotalStromCount"] intValue];
		    return self;
	}

    - (id) initWithFourSquareNode:(NSMutableDictionary *)FS_dict
    {
        self.FoursquareID = [FS_dict objectForKey:@"id"];
        self.Category =@"";
        self.EmailId = @"";
        self.IsAutoStrikeOn = NO;
        self.IsFavorite = NO;
        self.Latitude = [[FS_dict objectForKey:@"location"] valueForKey:@"lat"];
        self.longitude = [[FS_dict objectForKey:@"location"] valueForKey:@"lng"];
        if ([[FS_dict valueForKey:@"contact"] valueForKey:@"formattedPhone"]!=nil) {
            self.LocationAddress = [self converToBase64:[[FS_dict valueForKey:@"contact"] valueForKey:@"formattedPhone"]];
        }
        else{
            self.LocationAddress = @"";
        }
        self.LocationId = 0;
        self.LocationName = [FS_dict valueForKey:@"name"];
        
        self.Message = @"";
        self.PhoneNo = @"";
        [Foursquare2 venueGetPhotos:[FS_dict valueForKey:@"id"] limit:[NSNumber numberWithInteger:1] offset:nil callback:^(BOOL success, id result) {
            if (success) {
                NSDictionary *resultDictionry= result;
                NSArray *array=[[[resultDictionry objectForKey:@"response"] objectForKey:@"photos"]objectForKey:@"items"];
                
                if (array!=nil&&array.count) {
                    NSDictionary *imageDict=[array objectAtIndex:0];
                    //self.Photo=[self converToBase64:[NSString stringWithFormat:@"%@%@%@",[imageDict objectForKey:@"prefix"],@"300x300",[imageDict objectForKey:@"suffix"]]];
                    self.Photo=[NSString stringWithFormat:@"%@%@%@",[imageDict objectForKey:@"prefix"],@"300x300",[imageDict objectForKey:@"suffix"]];
                    
                }
            } else {
                self.Photo=@"";
            }
        }];
        
        
        self.Status = @"";
        NSMutableDictionary *hereNow=[FS_dict objectForKey:@"hereNow"];
        self.TotalStrike = [[hereNow valueForKey:@"count"]  intValue];
        self.TotalStrom = 1;
        self.UserId = 0;
        
        
        self.AverageAge = 0;
        self.AverageFemale = 0;
        self.AverageMale = 0;
        self.LargestStrikeCount = 0;
        self.TotalFemale = 0;
        self.TotalMale = 0;
        self.LargestStrikeCreatedDate = NULL;
        return self;
    }

    -(NSString *)converToBase64:(NSString*)str
    {
   // NSLog(@"before base 64=%@", str);
    NSString *base64String = nil;
    // NSData *data=[UIImage base64DataFromString:str];
    NSData* data = [str dataUsingEncoding:NSUTF8StringEncoding];
    base64String=[UIImage base64forData:data];
   // NSLog(@"after base64=%@",base64String);
    
    return base64String;
    }

	- (void) dealloc
	{
		self.AutoStrikeAlarmDate = nil;
		self.Category = nil;
		self.EmailId = nil;
		self.Latitude = nil;
		self.LocationAddress = nil;
		self.LocationList = nil;
		self.LocationName = nil;
		self.Message = nil;
		self.PhoneNo = nil;
		self.Photo = nil;
		self.Status = nil;
		self.longitude = nil;
		[super dealloc];
	}

@end
