/*
	Location.h
	The interface definition of properties and methods for the Location object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>
	
@class ArrayOfLocation;

@interface Location : NSObject
{
	NSDate* _AutoStrikeAlarmDate;
    NSDate* _LargestStrikeCreatedDate;
	NSString* _Category;
	NSString* _EmailId;
	BOOL _IsAutoStrikeOn;
	BOOL _IsFavorite;
	NSString* _Latitude;
	NSString* _LocationAddress;
	int _LocationId;
	NSMutableArray* _LocationList;
	NSString* _LocationName;
	NSString* _Message;
	NSString* _PhoneNo;
	NSString* _Photo;
	NSString* _Status;
	int _TotalStrike;
	int _TotalStrom;
    int _TotalStromCount;
	int _UserId;
	NSString* _longitude;
    int _TotalFemale;
    int _TotalMale;
    
    int _AverageAge;
    int _AverageFemale;
    int _AverageMale;
    int _LargestStrikeCount;
    
    
	
}
		
	@property (retain, nonatomic) NSDate* AutoStrikeAlarmDate;
    @property (retain, nonatomic) NSDate* LargestStrikeCreatedDate;
	@property (retain, nonatomic) NSString* Category;
	@property (retain, nonatomic) NSString* EmailId;
	@property BOOL IsAutoStrikeOn;
	@property BOOL IsFavorite;
	@property (retain, nonatomic) NSString* Latitude;
	@property (retain, nonatomic) NSString* LocationAddress;
	@property int LocationId;
	@property (retain, nonatomic) NSMutableArray* LocationList;
	@property (retain, nonatomic) NSString* LocationName;
	@property (retain, nonatomic) NSString* Message;
	@property (retain, nonatomic) NSString* PhoneNo;
	@property (retain, nonatomic) NSString* Photo;
	@property (retain, nonatomic) NSString* Status;
    @property (retain, nonatomic) NSString* FoursquareID;
    @property int TotalStrike;
	@property int TotalStrom;
    @property int TotalStromCount;
	@property int UserId;
    @property int TotalFemale;
    @property int TotalMale;
	@property (retain, nonatomic) NSString* longitude;

    @property int AverageAge;
    @property int AverageFemale;
    @property int AverageMale;
    @property int LargestStrikeCount;


	- (id) initWithNode: (NSMutableDictionary*) node;
   - (id) initWithFourSquareNode:(NSMutableDictionary *)FS_dict;

	

@end
