/*
	Strike.h
	The implementation of properties and methods for the Strike object.
	Generated by RRInnovation LLC
*/
#import "Strike.h"

#import "Location.h"
#import "User.h"
@implementation Strike
	@synthesize IsActive = _IsActive;
	@synthesize LocationDetails = _LocationDetails;
	@synthesize Message = _Message;
	@synthesize Status = _Status;
	@synthesize StrikeID = _StrikeID;
	@synthesize UserDetails = _UserDetails;
 
	- (id) init
	{
		if(self = [super init])
		{
			self.LocationDetails = nil; // [[Location alloc] init];
			self.Message = nil;
			self.Status = nil;
			self.UserDetails = nil; // [[User alloc] init];

		}
		return self;
	}

	
	- (id) initWithNode: (NSMutableDictionary*) node
    {
	        self.IsActive = [[node valueForKey: @"IsActive"] boolValue];
			self.LocationDetails = [node valueForKey: @"LocationDetails"];
			self.Message = [node valueForKey: @"Message"];
			self.Status = [node valueForKey: @"Status"];
			self.StrikeID = [[node valueForKey: @"StrikeID"] intValue];
			self.UserDetails = [node valueForKey: @"UserDetails"];
		    return self;
	}

    - (void) dealloc
	{
		self.LocationDetails = nil;
		self.Message = nil;
		self.Status = nil;
		self.UserDetails = nil;
        [super dealloc];
	}

@end
