/*
	Strike.h
	The interface definition of properties and methods for the Strike object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>
	
@class Location;
@class User;

@interface Strike : NSObject
{
	BOOL _IsActive;
	Location* _LocationDetails;
	NSString* _Message;
	NSString* _Status;
	int _StrikeID;
	User* _UserDetails;
	
}
		
	@property BOOL IsActive;
	@property (retain, nonatomic) Location* LocationDetails;
	@property (retain, nonatomic) NSString* Message;
	@property (retain, nonatomic) NSString* Status;
	@property int StrikeID;
	@property (retain, nonatomic) User* UserDetails;

- (id) initWithNode: (NSMutableDictionary*) node;

@end
